let navBar = '<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow"> <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="dashboard.html">Calero s Rental Car</a> <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> <div class="navbar-nav"> <div class="nav-item text-nowrap"> <a class="nav-link px-3" href="#">Sign out</a> </div> </div> </header>';
let nav = '<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"> <div class="position-sticky pt-3"> <ul class="nav flex-column"> <li class="nav-item"> <a class="nav-link" id = "linkDashboard" aria-current="page" href="dashboard.html" id="home"> <ion-icon name="home-outline"></ion-icon> Dashboard </a> </li> <li class="nav-item"> <a class="nav-link" id = "linkEmpleados" href="empleados.html"> <ion-icon name="people-circle-outline"></ion-icon> Empleados </a> </li> <li class="nav-item"> <a class="nav-link" id = "linkAutomoviles" href="automoviles.html"> <ion-icon name="car-sport-outline"></ion-icon> Automoviles </a> </li> <li class="nav-item"> <a class="nav-link" id = "linkClientes" href="clientes.html"> <ion-icon name="people-circle-outline"></ion-icon> Clientes </a> </li> <li class="nav-item"> <a class="nav-link" id = "linkRentaAutos" href="renta-automoviles.html"> <ion-icon name="cart-outline"></ion-icon> Renta de Automoviles </a> </li> <li class="nav-item"> <a class="nav-link" id = "linkMantenimientos" href="mantenimientos.html"> <ion-icon name="build-outline"></ion-icon> Mantenimientos </a> </li> <li class="nav-item"> <a class="nav-link" id = "linkReportes" href="reportes.html"> <ion-icon name="bar-chart-outline"></ion-icon> Reports </a> </li> <div class="mini-carousel"> <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel"> <div class="carousel-inner"> <div class="carousel-item active"> <img src="../../images/satisfaccion.jpg" class="d-block w-100" alt="..."> </div> <div class="carousel-item"> <img src="../../images/encuesta de satisfaccion.jpg" class="d-block w-100" alt="..."> </div> <div class="carousel-item"> <img src="../../images/satisfaccion-2.jpg" class="d-block w-100" alt="..."> </div> </div> </div> </div> </div> </nav>';

function loadNavBar(){
    $('header').html(navBar);
    $('nav').html(nav);
}

$(function() {
    console.log("Pagina lista");
    loadNavBar();
});

